### ISSUE TITLE
你好，你的这个规则，可以转换为clashx 的配置文件吗？

### ISSUE THREAD

**Issue by zq500480** [yawenchim/QuantumultX-mix#3]
你好，你的这个规则，可以转换为clashx 的配置文件吗？谢谢

**Comment by yawenchim** [comment]
你去库里找我Clash的规则，QuanX的为啥要套进ClashX使用呢。

**Comment by zq500480** [comment]
我QuantumultX,找了很多规则，感觉还是你的很好用，其他的都不方便分类。
我想电脑上使用的clash X也用这个规则，刚翻看没找到，我去库里再找找
再次感谢回复，谢谢。

**Comment by yawenchim** [comment]
因为QuanX规则里面会涉及到脚本那些，而Clash X并不包含这些
Clash我写的是这个地址https://raw.githubusercontent.com/yawenchim/Clash/master/YattaClash.ini
你使用转换API配合你的订阅就可以使用了，不懂的话可以去我的博客看看有Clash的教程。

**Comment by zq500480** [comment]
好的，可否发下博客地址，之前没保存过，谢谢

**Comment by yawenchim** [comment]
https://yattazen.com/tutorial/clash-custom-config.html

**Comment by zq500480** [comment]
收到，先去研究下

**Comment by zq500480** [comment]
你好，按照博客介绍，使用https://sub.dler.io/，转换你的Ini文件，和我的订阅，添加到clashx,有一个报错，无法运行
<img width="579" alt="image" src="https://github.com/yawenchim/QuantumultX-mix/assets/34306818/c3f28420-2870-4982-997b-0f35b5e1e345">

**Comment by yawenchim** [comment]
去看114行写的啥

**Comment by zq500480** [comment]
重启可以了，<img width="348" alt="image" src="https://github.com/yawenchim/QuantumultX-mix/assets/34306818/f93d4c60-10cb-4955-a479-765cc5f438fa">

**Comment by zq500480** [comment]
我想手动加些自己的节点，也必须写成一行行的形式吗，
<img width="736" alt="image" src="https://github.com/yawenchim/QuantumultX-mix/assets/34306818/9d52f2b0-ee75-43da-9d9e-01e9d095bf14">
，我看路由器里插件都是写的竖着的模式，
<img width="549" alt="image" src="https://github.com/yawenchim/QuantumultX-mix/assets/34306818/4d5fb14d-1ecd-42b9-943a-072e30a65fd3">

**Comment by zq500480** [comment]
<img width="364" alt="image" src="https://github.com/yawenchim/QuantumultX-mix/assets/34306818/581d4234-5188-4612-987b-ed61ea3cec97">
，bu'zhi'd不知道哪里设置问题，开启这个clashx github都无法访问

**Comment by yawenchim** [comment]
试试漏网之鱼走代理

**Comment by zq500480** [comment]
好的，十分感谢，那个代理服务器的，在这配置里面，只能横着写吗？

**Comment by yawenchim** [comment]
ClashX不常用  不太清楚  如果他不生效应该就只能横写

**Comment by yawenchim** [comment]
另外 如果自己加节点 我几点是把你那些节点做成订阅的模式，我另一篇文章有教，不然你节点自己加本地配置里头容易被在线的覆盖

**Comment by zq500480** [comment]
好的，那个开启后无法访问原因是这样的，不知道什么原因，节点经过转换，好像少了什么参数，全部不可用了
<img width="629" alt="image" src="https://github.com/yawenchim/QuantumultX-mix/assets/34306818/c89f1ae5-5a87-4234-bc82-1647edeb3141">

**Comment by yawenchim** [comment]
转换API有些协议不知道 大部分VMESS可以 其他的你检查系统时间吧

**Comment by zq500480** [comment]
有支持trojan的转换吗，机场都是trojan模式

**Comment by yawenchim** [comment]
自己Google吧

**Comment by zq500480** [comment]
好的，多谢
